// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType]
}
/** Content for Post documents */
interface PostDocumentData {
  /**
   * Title field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField
  /**
   * Slice Zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PostDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismic.KeyTextField
  /**
   * Meta Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>
  /**
   * Meta Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField
}
/**
 * Slice for *Post → Slice Zone*
 *
 */
type PostDocumentDataSlicesSlice = ContentSlice | GlossarySlice
/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, 'post', Lang>
export type AllDocumentTypes = PostDocument
/**
 * Item in Content → Items
 *
 */
export interface ContentSliceDefaultItem {
  /**
   * TitleContent field in *Content → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].titlecontent
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  titlecontent: prismic.RichTextField
  /**
   * Body field in *Content → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.items[].body
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  body: prismic.RichTextField
}
/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ContentSliceDefaultItem>
>
/**
 * Slice variation for *Content*
 *
 */
type ContentSliceVariation = ContentSliceDefault
/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: `Content`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContentSlice = prismic.SharedSlice<'content', ContentSliceVariation>
/**
 * Item in Glossary → Items
 *
 */
export interface GlossarySliceDefaultItem {
  /**
   * TitleGlossary field in *Glossary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: glossary.items[].titleglossary
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  titleglossary: prismic.RichTextField
  /**
   * ContentGlossary field in *Glossary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: glossary.items[].contentglossary
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  contentglossary: prismic.RichTextField
}
/**
 * Default variation for Glossary Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GlossarySliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<GlossarySliceDefaultItem>
>
/**
 * Slice variation for *Glossary*
 *
 */
type GlossarySliceVariation = GlossarySliceDefault
/**
 * Glossary Shared Slice
 *
 * - **API ID**: `glossary`
 * - **Description**: `Glossary`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GlossarySlice = prismic.SharedSlice<
  'glossary',
  GlossarySliceVariation
>
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }
  namespace Content {
    export type {
      PostDocumentData,
      PostDocumentDataSlicesSlice,
      PostDocument,
      AllDocumentTypes,
      ContentSliceDefaultItem,
      ContentSliceDefault,
      ContentSliceVariation,
      ContentSlice,
      GlossarySliceDefaultItem,
      GlossarySliceDefault,
      GlossarySliceVariation,
      GlossarySlice,
    }
  }
}
