// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  content: dynamic(() => import('./Content')),
  glossary: dynamic(() => import('./Glossary')),
}
